# Configuration file
# Accesss the BIDSifying Github page for more information: https://github.com/NILAB-UvA/bidsify

options:
    mri_ext: nifti  # alternatives: nifti/dcm/DICOM
    debug: True  # alternative: True, prints out a lot of stuff
    n_cores: -1  # number of CPU cores to use (for some operations)
    subject_stem: sub  # subject identifier
    deface: True  # whether to deface structural scans
    spinoza_data: False  # only relevant for data acquired at the Spinoza Centre
    out_dir: bidstwo

mappings:
    bold: _bold
    T1w: _t1
    dwi: _DWI
    T2w: _t2
    MPRAGE: _MPRAGE


metadata:  # will be appended to EACH file
    MagneticFieldStrength: 3
    ParallelAcquisitionTechnique: SENSE
    BIDSVersion: '1.1.0'
    InstitutionName: you_institution_name

# Anatomical data
anat: 

  MPRAGE:
    id: MPRAGE
    acq: MPRAGE_T1w

  First_T1:
    id: t1_fl2d_intra_plane 
    acq: fl2dtrainplane 
    run: 1

  Second_T1:
    id: t1_fl2d_tra_inplane
    acq: fl2dtrainplane
    run: 2

  First_T2:
    id: t2_space_cor_p2_iso  
    acq: spacecorp2iso  
    run: 1

  Second_T2:
    id: t2_space_cor_p2_iso  
    acq: spacecorp2iso  
    run: 2

# Diffiusion Weighted imaging data 
dwi:

  First_DWI_AP: 
    id: _DWI_AP_
    run: 1

  Second_DWI_AP: 
    id: _DWI_AP_
    run: 2

  First_DWI_b0_PA:
    id: _DWI_b0_PA_
    run: 1 

# Functional data 
func:

  # Basic metadata characteristics 
  metadata:
    EffectiveEchoSpacing: 0.00365
    PhaseEncodingDirection: "j"

  # Resting State scans
  First_RestingState: 
    id: RestingState_ep2d_bold_moco_p2_s2 
    task: RestingState
    run: 1
    
  Second_RestingState:
    id: RestingState_ep2d_bold_moco_p2_s2
    task: RestingState
    run: 2

  # Retinotopic Mapping task 

  First_RET:
    id: ep2d_bold_moco_RET
    task: RET
    run: 1

  Second_RET:
    id: ep2d_bold_moco_RET
    task: RET
    run: 2
    
  Third_RET:
    id: ep2d_bold_moco_RET
    task: RET
    run: 3

  Fourth_RET:
    id: ep2d_bold_moco_RET
    task: RET
    run: 4